name: nus_nextbus_persistence
description: A sample command-line application.
version: 0.0.1
#homepage: https://www.example.com
#author: User <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  nus_nextbus_api:
    git: https://github.com/jiachen247/nus-nextbus-api.git

dev_dependencies:
  test: ^0.12.0
